name: CI
on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  helm_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Helm Chart Releaser
        uses: helm/chart-releaser-action@v1.1.0
        env:
          CR_TOKEN: "${{ secrets.GH_ACTIONS_TOKEN }}"
        with:
          # The GitHub Pages URL to the charts repo (default: https://<owner>.github.io/<repo>)
          charts_repo_url: https://github.com/jfdona23/helm-personal-repo
